### ISSUE TITLE
Upgrade mm_createstp.sas to create Type 2 stored processes

### ISSUE THREAD

**Issue by emil-ufa** [Boemska/macrocore#6]
Hi!
I have a question about the macro macrocore/meta/mm_createstp.sas.

The macro mentions this:
>     To upgrade this macro to work with type 2 (which can embed SAS code
>     and is compabitible with SAS from 9.3 onwards) then the UsageVersion should
>     change to 2000000 and the TextStore object updated.  The ComputeServer
>     reference will also be to ServerContext rather than LogicalServer.

This explanation is a bit vague.

**Q**: what exact actions should I perform to change the macro to create Type 2 stored processes?
1. "switch 1000000 to 2000000" - got it;
2. "TextStore object updated" - what does it mean?
3. "The ComputeServer reference will also be to ServerContext rather than LogicalServer" - as far as I see it, all strings "ServerContext" in code should be replaced with "LogicalServer". Is that right?

Are the steps 1, 2, 3 enough?

I made steps 1 and 3, and it resulted in corrupt metadata for stored process. Now I cannot delete it :D

I would really appreciate if you mention some SAS docs which could help in understanding your code. I managed to find almost none.

**Comment by allanbowe** [comment]
Hi @emil-ufa!  The `TextStore` object is where the actual STP code would be stored (this is what I mean by 'updated').  Regarding your third point, I think there's more to it than that but I'd need to investigate.

The reason the macro is not updated to Type 2 is simply that I ran out of time, however I do plan to revisit this in the next month or two.  Corrupt metadata is a real problem when playing with these kind of functions, so be sure to only develop this kind of stuff in a 'throwaway' environment. You can delete your metadata objects though using metabrowse (you'll need to enable the delete option).

The following SAS doc is best for understanding metadata structure:  https://support.sas.com/documentation/cdl/en/omamodref/67417/HTML/default/viewer.htm#hierlist.htm

Selerity also have some great macros for querying metadata:  https://seleritysas.com/data-step-view-of-email-addresses-in-sas-metadata/

BTW - if you figure this out - do please submit a pull request!

**Comment by emil-ufa** [comment]
@allanbowe Thanks a lot!

**Comment by allanbowe** [comment]
reopening - will close once we upgrade the macro!

**Comment by emil-ufa** [comment]
That's the spirit! :D
